// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type DeviceLinkToken struct {
	ID            int64         `json:"id"`
	TokenHash     []byte        `json:"token_hash"`
	UserID        int64         `json:"user_id"`
	ExpiresAtUtc  int64         `json:"expires_at_utc"`
	RedeemedAtUtc sql.NullInt64 `json:"redeemed_at_utc"`
	UsedAtUtc     sql.NullInt64 `json:"used_at_utc"`
	CreatedAtUtc  int64         `json:"created_at_utc"`
}

type Entry struct {
	ID                    int64          `json:"id"`
	UserID                int64          `json:"user_id"`
	RecordedAtUtc         int64          `json:"recorded_at_utc"`
	TimezoneOffsetMinutes int64          `json:"timezone_offset_minutes"`
	EntryDate             string         `json:"entry_date"`
	NoteText              sql.NullString `json:"note_text"`
	IsPrivate             int64          `json:"is_private"`
	IsDraft               int64          `json:"is_draft"`
	AudioFilePath         sql.NullString `json:"audio_file_path"`
	TranscriptionStatus   string         `json:"transcription_status"`
	CreatedAtUtc          int64          `json:"created_at_utc"`
}

type Setting struct {
	ID            int64          `json:"id"`
	UserID        int64          `json:"user_id"`
	SettingsKey   string         `json:"settings_key"`
	SettingsValue sql.NullString `json:"settings_value"`
	CreatedAtUtc  int64          `json:"created_at_utc"`
}

type TrackableDailyDismissal struct {
	ID                    int64  `json:"id"`
	UserID                int64  `json:"user_id"`
	TrackableDefinitionID int64  `json:"trackable_definition_id"`
	DismissalDate         string `json:"dismissal_date"`
	Dismissed             int64  `json:"dismissed"`
	CreatedAtUtc          int64  `json:"created_at_utc"`
	UpdatedAtUtc          int64  `json:"updated_at_utc"`
}

type TrackableDefinition struct {
	ID           int64          `json:"id"`
	UserID       int64          `json:"user_id"`
	TemplateID   sql.NullInt64  `json:"template_id"`
	Name         string         `json:"name"`
	Icon         sql.NullString `json:"icon"`
	ValueType    string         `json:"value_type"`
	Unit         sql.NullString `json:"unit"`
	MinValue     sql.NullInt64  `json:"min_value"`
	MaxValue     sql.NullInt64  `json:"max_value"`
	IsSensitive  int64          `json:"is_sensitive"`
	PrivateLabel sql.NullString `json:"private_label"`
	Category     string         `json:"category"`
	Active       int64          `json:"active"`
	CreatedAtUtc int64          `json:"created_at_utc"`
}

type TrackableTemplate struct {
	ID                int64          `json:"id"`
	Name              string         `json:"name"`
	ValueType         string         `json:"value_type"`
	Unit              sql.NullString `json:"unit"`
	MinValue          sql.NullInt64  `json:"min_value"`
	MaxValue          sql.NullInt64  `json:"max_value"`
	Icon              sql.NullString `json:"icon"`
	IsSensitive       int64          `json:"is_sensitive"`
	PrivateLabel      sql.NullString `json:"private_label"`
	CustomControlType sql.NullString `json:"custom_control_type"`
	Category          sql.NullString `json:"category"`
	CreatedAtUtc      int64          `json:"created_at_utc"`
}

type TrackableValue struct {
	ID                    int64          `json:"id"`
	EntryID               int64          `json:"entry_id"`
	TrackableDefinitionID int64          `json:"trackable_definition_id"`
	ValueInt              sql.NullInt64  `json:"value_int"`
	ValueBool             sql.NullInt64  `json:"value_bool"`
	ValueText             sql.NullString `json:"value_text"`
	LocationText          sql.NullString `json:"location_text"`
	NoteText              sql.NullString `json:"note_text"`
	EntryDate             sql.NullString `json:"entry_date"`
	CreatedAtUtc          int64          `json:"created_at_utc"`
	UpdatedAtUtc          sql.NullInt64  `json:"updated_at_utc"`
}

type User struct {
	ID             int64          `json:"id"`
	CreatedAtUtc   int64          `json:"created_at_utc"`
	WebauthnUserID []byte         `json:"webauthn_user_id"`
	DisplayName    sql.NullString `json:"display_name"`
	Timezone       sql.NullString `json:"timezone"`
}

type WebauthnCredential struct {
	ID           int64          `json:"id"`
	UserID       int64          `json:"user_id"`
	CredentialID []byte         `json:"credential_id"`
	PublicKey    []byte         `json:"public_key"`
	SignCount    int64          `json:"sign_count"`
	Flags        sql.NullString `json:"flags"`
	Transports   sql.NullString `json:"transports"`
	CreatedAtUtc int64          `json:"created_at_utc"`
}
