// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createDraftEntry = `-- name: CreateDraftEntry :one
INSERT INTO entries (
    user_id,
    recorded_at_utc,
    timezone_offset_minutes,
    entry_date,
    note_text,
    is_private,
    is_draft,
    audio_file_path,
    transcription_status,
    created_at_utc
)
VALUES (?, ?, ?, ?, NULL, 0, 1, ?, 'pending', ?)
RETURNING id, user_id, recorded_at_utc, timezone_offset_minutes, entry_date, note_text, is_private, is_draft, audio_file_path, transcription_status, created_at_utc
`

type CreateDraftEntryParams struct {
	UserID                int64          `json:"user_id"`
	RecordedAtUtc         int64          `json:"recorded_at_utc"`
	TimezoneOffsetMinutes int64          `json:"timezone_offset_minutes"`
	EntryDate             string         `json:"entry_date"`
	AudioFilePath         sql.NullString `json:"audio_file_path"`
	CreatedAtUtc          int64          `json:"created_at_utc"`
}

func (q *Queries) CreateDraftEntry(ctx context.Context, arg CreateDraftEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, createDraftEntry,
		arg.UserID,
		arg.RecordedAtUtc,
		arg.TimezoneOffsetMinutes,
		arg.EntryDate,
		arg.AudioFilePath,
		arg.CreatedAtUtc,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RecordedAtUtc,
		&i.TimezoneOffsetMinutes,
		&i.EntryDate,
		&i.NoteText,
		&i.IsPrivate,
		&i.IsDraft,
		&i.AudioFilePath,
		&i.TranscriptionStatus,
		&i.CreatedAtUtc,
	)
	return i, err
}

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (
    user_id,
    recorded_at_utc,
    timezone_offset_minutes,
    entry_date,
    note_text,
    is_private,
    created_at_utc
)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, recorded_at_utc, timezone_offset_minutes, entry_date, note_text, is_private, is_draft, audio_file_path, transcription_status, created_at_utc
`

type CreateEntryParams struct {
	UserID                int64          `json:"user_id"`
	RecordedAtUtc         int64          `json:"recorded_at_utc"`
	TimezoneOffsetMinutes int64          `json:"timezone_offset_minutes"`
	EntryDate             string         `json:"entry_date"`
	NoteText              sql.NullString `json:"note_text"`
	IsPrivate             int64          `json:"is_private"`
	CreatedAtUtc          int64          `json:"created_at_utc"`
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, createEntry,
		arg.UserID,
		arg.RecordedAtUtc,
		arg.TimezoneOffsetMinutes,
		arg.EntryDate,
		arg.NoteText,
		arg.IsPrivate,
		arg.CreatedAtUtc,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RecordedAtUtc,
		&i.TimezoneOffsetMinutes,
		&i.EntryDate,
		&i.NoteText,
		&i.IsPrivate,
		&i.IsDraft,
		&i.AudioFilePath,
		&i.TranscriptionStatus,
		&i.CreatedAtUtc,
	)
	return i, err
}

const createTrackableDefinition = `-- name: CreateTrackableDefinition :one
INSERT INTO trackable_definitions (
    user_id,
    template_id,
    name,
    value_type,
    unit,
    min_value,
    max_value,
    icon,
    category,
    is_sensitive,
    private_label,
    created_at_utc
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, template_id, name, icon, value_type, unit, min_value, max_value, is_sensitive, private_label, category, active, created_at_utc
`

type CreateTrackableDefinitionParams struct {
	UserID       int64          `json:"user_id"`
	TemplateID   sql.NullInt64  `json:"template_id"`
	Name         string         `json:"name"`
	ValueType    string         `json:"value_type"`
	Unit         sql.NullString `json:"unit"`
	MinValue     sql.NullInt64  `json:"min_value"`
	MaxValue     sql.NullInt64  `json:"max_value"`
	Icon         sql.NullString `json:"icon"`
	Category     string         `json:"category"`
	IsSensitive  int64          `json:"is_sensitive"`
	PrivateLabel sql.NullString `json:"private_label"`
	CreatedAtUtc int64          `json:"created_at_utc"`
}

func (q *Queries) CreateTrackableDefinition(ctx context.Context, arg CreateTrackableDefinitionParams) (TrackableDefinition, error) {
	row := q.db.QueryRowContext(ctx, createTrackableDefinition,
		arg.UserID,
		arg.TemplateID,
		arg.Name,
		arg.ValueType,
		arg.Unit,
		arg.MinValue,
		arg.MaxValue,
		arg.Icon,
		arg.Category,
		arg.IsSensitive,
		arg.PrivateLabel,
		arg.CreatedAtUtc,
	)
	var i TrackableDefinition
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TemplateID,
		&i.Name,
		&i.Icon,
		&i.ValueType,
		&i.Unit,
		&i.MinValue,
		&i.MaxValue,
		&i.IsSensitive,
		&i.PrivateLabel,
		&i.Category,
		&i.Active,
		&i.CreatedAtUtc,
	)
	return i, err
}

const createTrackableValue = `-- name: CreateTrackableValue :one
INSERT INTO trackable_values (
    entry_id,
    trackable_definition_id,
    value_int,
    value_bool,
    value_text,
    created_at_utc
)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, entry_id, trackable_definition_id, value_int, value_bool, value_text, location_text, note_text, entry_date, created_at_utc, updated_at_utc
`

type CreateTrackableValueParams struct {
	EntryID               int64          `json:"entry_id"`
	TrackableDefinitionID int64          `json:"trackable_definition_id"`
	ValueInt              sql.NullInt64  `json:"value_int"`
	ValueBool             sql.NullInt64  `json:"value_bool"`
	ValueText             sql.NullString `json:"value_text"`
	CreatedAtUtc          int64          `json:"created_at_utc"`
}

func (q *Queries) CreateTrackableValue(ctx context.Context, arg CreateTrackableValueParams) (TrackableValue, error) {
	row := q.db.QueryRowContext(ctx, createTrackableValue,
		arg.EntryID,
		arg.TrackableDefinitionID,
		arg.ValueInt,
		arg.ValueBool,
		arg.ValueText,
		arg.CreatedAtUtc,
	)
	var i TrackableValue
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.TrackableDefinitionID,
		&i.ValueInt,
		&i.ValueBool,
		&i.ValueText,
		&i.LocationText,
		&i.NoteText,
		&i.EntryDate,
		&i.CreatedAtUtc,
		&i.UpdatedAtUtc,
	)
	return i, err
}

const deleteEntriesByUser = `-- name: DeleteEntriesByUser :exec
DELETE FROM entries
WHERE user_id = ?
`

func (q *Queries) DeleteEntriesByUser(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteEntriesByUser, userID)
	return err
}

const deleteEntry = `-- name: DeleteEntry :exec
DELETE FROM entries
WHERE id = ? AND user_id = ?
`

type DeleteEntryParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteEntry(ctx context.Context, arg DeleteEntryParams) error {
	_, err := q.db.ExecContext(ctx, deleteEntry, arg.ID, arg.UserID)
	return err
}

const deleteSettingsByUser = `-- name: DeleteSettingsByUser :exec
DELETE FROM settings
WHERE user_id = ?
`

func (q *Queries) DeleteSettingsByUser(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteSettingsByUser, userID)
	return err
}

const deleteTrackableDailyDismissalsByUser = `-- name: DeleteTrackableDailyDismissalsByUser :exec
DELETE FROM trackable_daily_dismissals
WHERE user_id = ?
`

func (q *Queries) DeleteTrackableDailyDismissalsByUser(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTrackableDailyDismissalsByUser, userID)
	return err
}

const deleteTrackableDefinitionsByUser = `-- name: DeleteTrackableDefinitionsByUser :exec
DELETE FROM trackable_definitions
WHERE user_id = ?
`

func (q *Queries) DeleteTrackableDefinitionsByUser(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTrackableDefinitionsByUser, userID)
	return err
}

const deleteTrackableValuesByUser = `-- name: DeleteTrackableValuesByUser :exec
DELETE FROM trackable_values
WHERE entry_id IN (
    SELECT id
    FROM entries
    WHERE entries.user_id = ?1
)
OR trackable_definition_id IN (
    SELECT id
    FROM trackable_definitions
    WHERE trackable_definitions.user_id = ?1
)
`

func (q *Queries) DeleteTrackableValuesByUser(ctx context.Context, targetUserID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTrackableValuesByUser, targetUserID)
	return err
}

const deleteWebauthnCredentialsByUser = `-- name: DeleteWebauthnCredentialsByUser :exec
DELETE FROM webauthn_credentials
WHERE user_id = ?
`

func (q *Queries) DeleteWebauthnCredentialsByUser(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteWebauthnCredentialsByUser, userID)
	return err
}

const findEntryTrackableValue = `-- name: FindEntryTrackableValue :one
SELECT tv.id, tv.entry_id, tv.trackable_definition_id, tv.value_int, tv.value_bool, tv.value_text, tv.location_text, tv.note_text, tv.entry_date, tv.created_at_utc, tv.updated_at_utc
FROM trackable_values tv
JOIN entries e ON e.id = tv.entry_id
WHERE tv.entry_id = ?
    AND tv.trackable_definition_id = ?
    AND e.user_id = ?
ORDER BY tv.created_at_utc DESC
LIMIT 1
`

type FindEntryTrackableValueParams struct {
	EntryID               int64 `json:"entry_id"`
	TrackableDefinitionID int64 `json:"trackable_definition_id"`
	UserID                int64 `json:"user_id"`
}

func (q *Queries) FindEntryTrackableValue(ctx context.Context, arg FindEntryTrackableValueParams) (TrackableValue, error) {
	row := q.db.QueryRowContext(ctx, findEntryTrackableValue, arg.EntryID, arg.TrackableDefinitionID, arg.UserID)
	var i TrackableValue
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.TrackableDefinitionID,
		&i.ValueInt,
		&i.ValueBool,
		&i.ValueText,
		&i.LocationText,
		&i.NoteText,
		&i.EntryDate,
		&i.CreatedAtUtc,
		&i.UpdatedAtUtc,
	)
	return i, err
}

const findRecentTrackableValue = `-- name: FindRecentTrackableValue :one
SELECT tv.id, tv.entry_id, tv.trackable_definition_id, tv.value_int, tv.value_bool, tv.value_text, tv.location_text, tv.note_text, tv.entry_date, tv.created_at_utc, tv.updated_at_utc
FROM trackable_values tv
JOIN entries e ON e.id = tv.entry_id
WHERE tv.trackable_definition_id = ?
  AND e.user_id = ?
  AND tv.created_at_utc >= ?
ORDER BY tv.created_at_utc DESC
LIMIT 1
`

type FindRecentTrackableValueParams struct {
	TrackableDefinitionID int64 `json:"trackable_definition_id"`
	UserID                int64 `json:"user_id"`
	CreatedAtUtc          int64 `json:"created_at_utc"`
}

func (q *Queries) FindRecentTrackableValue(ctx context.Context, arg FindRecentTrackableValueParams) (TrackableValue, error) {
	row := q.db.QueryRowContext(ctx, findRecentTrackableValue, arg.TrackableDefinitionID, arg.UserID, arg.CreatedAtUtc)
	var i TrackableValue
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.TrackableDefinitionID,
		&i.ValueInt,
		&i.ValueBool,
		&i.ValueText,
		&i.LocationText,
		&i.NoteText,
		&i.EntryDate,
		&i.CreatedAtUtc,
		&i.UpdatedAtUtc,
	)
	return i, err
}

const getAvailableTrackableTemplateByID = `-- name: GetAvailableTrackableTemplateByID :one
SELECT tt.id, tt.name, tt.value_type, tt.unit, tt.min_value, tt.max_value, tt.icon, tt.is_sensitive, tt.private_label, tt.custom_control_type, tt.category, tt.created_at_utc
FROM trackable_templates tt
LEFT JOIN trackable_definitions td
        ON td.template_id = tt.id
     AND td.user_id = ?
WHERE tt.id = ?
    AND td.id IS NULL
`

type GetAvailableTrackableTemplateByIDParams struct {
	UserID int64 `json:"user_id"`
	ID     int64 `json:"id"`
}

func (q *Queries) GetAvailableTrackableTemplateByID(ctx context.Context, arg GetAvailableTrackableTemplateByIDParams) (TrackableTemplate, error) {
	row := q.db.QueryRowContext(ctx, getAvailableTrackableTemplateByID, arg.UserID, arg.ID)
	var i TrackableTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ValueType,
		&i.Unit,
		&i.MinValue,
		&i.MaxValue,
		&i.Icon,
		&i.IsSensitive,
		&i.PrivateLabel,
		&i.CustomControlType,
		&i.Category,
		&i.CreatedAtUtc,
	)
	return i, err
}

const getEntryByID = `-- name: GetEntryByID :one
SELECT id, user_id, recorded_at_utc, timezone_offset_minutes, entry_date, note_text, is_private, is_draft, audio_file_path, transcription_status, created_at_utc
FROM entries
WHERE id = ? AND user_id = ?
`

type GetEntryByIDParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetEntryByID(ctx context.Context, arg GetEntryByIDParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getEntryByID, arg.ID, arg.UserID)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RecordedAtUtc,
		&i.TimezoneOffsetMinutes,
		&i.EntryDate,
		&i.NoteText,
		&i.IsPrivate,
		&i.IsDraft,
		&i.AudioFilePath,
		&i.TranscriptionStatus,
		&i.CreatedAtUtc,
	)
	return i, err
}

const getEntryWithTrackables = `-- name: GetEntryWithTrackables :many
SELECT
    e.id,
    e.user_id,
    e.recorded_at_utc,
    e.timezone_offset_minutes,
    e.entry_date,
    e.note_text,
    e.is_private,
    e.is_draft,
    e.audio_file_path,
    e.transcription_status,
    e.created_at_utc,
    tv.id AS trackable_value_id,
    tv.trackable_definition_id,
    tv.value_int,
    tv.value_bool,
    tv.value_text,
    tv.location_text,
    tv.note_text AS trackable_note_text,
    tv.entry_date AS trackable_entry_date,
    tv.created_at_utc AS trackable_created_at_utc,
    tv.updated_at_utc AS trackable_updated_at_utc,
    td.name AS trackable_name,
    td.icon AS trackable_icon,
    td.value_type AS trackable_value_type,
    td.unit AS trackable_unit
FROM entries e
LEFT JOIN trackable_values tv ON tv.entry_id = e.id
LEFT JOIN trackable_definitions td ON td.id = tv.trackable_definition_id
WHERE e.user_id = ? AND e.id = ?
ORDER BY tv.created_at_utc ASC
`

type GetEntryWithTrackablesParams struct {
	UserID int64 `json:"user_id"`
	ID     int64 `json:"id"`
}

type GetEntryWithTrackablesRow struct {
	ID                    int64          `json:"id"`
	UserID                int64          `json:"user_id"`
	RecordedAtUtc         int64          `json:"recorded_at_utc"`
	TimezoneOffsetMinutes int64          `json:"timezone_offset_minutes"`
	EntryDate             string         `json:"entry_date"`
	NoteText              sql.NullString `json:"note_text"`
	IsPrivate             int64          `json:"is_private"`
	IsDraft               int64          `json:"is_draft"`
	AudioFilePath         sql.NullString `json:"audio_file_path"`
	TranscriptionStatus   string         `json:"transcription_status"`
	CreatedAtUtc          int64          `json:"created_at_utc"`
	TrackableValueID      sql.NullInt64  `json:"trackable_value_id"`
	TrackableDefinitionID sql.NullInt64  `json:"trackable_definition_id"`
	ValueInt              sql.NullInt64  `json:"value_int"`
	ValueBool             sql.NullInt64  `json:"value_bool"`
	ValueText             sql.NullString `json:"value_text"`
	LocationText          sql.NullString `json:"location_text"`
	TrackableNoteText     sql.NullString `json:"trackable_note_text"`
	TrackableEntryDate    sql.NullString `json:"trackable_entry_date"`
	TrackableCreatedAtUtc sql.NullInt64  `json:"trackable_created_at_utc"`
	TrackableUpdatedAtUtc sql.NullInt64  `json:"trackable_updated_at_utc"`
	TrackableName         sql.NullString `json:"trackable_name"`
	TrackableIcon         sql.NullString `json:"trackable_icon"`
	TrackableValueType    sql.NullString `json:"trackable_value_type"`
	TrackableUnit         sql.NullString `json:"trackable_unit"`
}

func (q *Queries) GetEntryWithTrackables(ctx context.Context, arg GetEntryWithTrackablesParams) ([]GetEntryWithTrackablesRow, error) {
	rows, err := q.db.QueryContext(ctx, getEntryWithTrackables, arg.UserID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEntryWithTrackablesRow
	for rows.Next() {
		var i GetEntryWithTrackablesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RecordedAtUtc,
			&i.TimezoneOffsetMinutes,
			&i.EntryDate,
			&i.NoteText,
			&i.IsPrivate,
			&i.IsDraft,
			&i.AudioFilePath,
			&i.TranscriptionStatus,
			&i.CreatedAtUtc,
			&i.TrackableValueID,
			&i.TrackableDefinitionID,
			&i.ValueInt,
			&i.ValueBool,
			&i.ValueText,
			&i.LocationText,
			&i.TrackableNoteText,
			&i.TrackableEntryDate,
			&i.TrackableCreatedAtUtc,
			&i.TrackableUpdatedAtUtc,
			&i.TrackableName,
			&i.TrackableIcon,
			&i.TrackableValueType,
			&i.TrackableUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrackableById = `-- name: GetTrackableById :one
SELECT id, user_id, template_id, name, icon, value_type, unit, min_value, max_value, is_sensitive, private_label, category, active, created_at_utc
FROM trackable_definitions
WHERE id = ? AND user_id = ?
`

type GetTrackableByIdParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetTrackableById(ctx context.Context, arg GetTrackableByIdParams) (TrackableDefinition, error) {
	row := q.db.QueryRowContext(ctx, getTrackableById, arg.ID, arg.UserID)
	var i TrackableDefinition
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TemplateID,
		&i.Name,
		&i.Icon,
		&i.ValueType,
		&i.Unit,
		&i.MinValue,
		&i.MaxValue,
		&i.IsSensitive,
		&i.PrivateLabel,
		&i.Category,
		&i.Active,
		&i.CreatedAtUtc,
	)
	return i, err
}

const getTrackableTemplates = `-- name: GetTrackableTemplates :many
SELECT tt.id, tt.name, tt.value_type, tt.unit, tt.min_value, tt.max_value, tt.icon, tt.is_sensitive, tt.private_label, tt.custom_control_type, tt.category, tt.created_at_utc
FROM trackable_templates tt
LEFT JOIN trackable_definitions td
        ON td.template_id = tt.id
     AND td.user_id = ?
WHERE td.id IS NULL
`

func (q *Queries) GetTrackableTemplates(ctx context.Context, userID int64) ([]TrackableTemplate, error) {
	rows, err := q.db.QueryContext(ctx, getTrackableTemplates, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrackableTemplate
	for rows.Next() {
		var i TrackableTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ValueType,
			&i.Unit,
			&i.MinValue,
			&i.MaxValue,
			&i.Icon,
			&i.IsSensitive,
			&i.PrivateLabel,
			&i.CustomControlType,
			&i.Category,
			&i.CreatedAtUtc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntries = `-- name: ListEntries :many
SELECT
    e.id,
    e.user_id,
    e.recorded_at_utc,
    e.timezone_offset_minutes,
    e.entry_date,
    e.note_text,
    e.is_private,
    e.is_draft,
    e.audio_file_path,
    e.transcription_status,
    e.created_at_utc,
    tv.id AS trackable_value_id,
    tv.trackable_definition_id,
    tv.value_int,
    tv.value_bool,
    tv.value_text,
    tv.location_text,
    tv.note_text AS trackable_note_text,
    tv.entry_date AS trackable_entry_date,
    tv.created_at_utc AS trackable_created_at_utc,
    tv.updated_at_utc AS trackable_updated_at_utc,
    td.name AS trackable_name,
    td.icon AS trackable_icon,
    td.value_type AS trackable_value_type,
    td.unit AS trackable_unit
FROM entries e
LEFT JOIN trackable_values tv ON tv.entry_id = e.id
LEFT JOIN trackable_definitions td ON td.id = tv.trackable_definition_id
WHERE e.user_id = ?1
    AND (CAST(?2 AS TEXT) = '' OR e.entry_date = CAST(?2 AS TEXT))
ORDER BY e.recorded_at_utc DESC, tv.created_at_utc ASC
`

type ListEntriesParams struct {
	UserID    int64  `json:"user_id"`
	EntryDate string `json:"entry_date"`
}

type ListEntriesRow struct {
	ID                    int64          `json:"id"`
	UserID                int64          `json:"user_id"`
	RecordedAtUtc         int64          `json:"recorded_at_utc"`
	TimezoneOffsetMinutes int64          `json:"timezone_offset_minutes"`
	EntryDate             string         `json:"entry_date"`
	NoteText              sql.NullString `json:"note_text"`
	IsPrivate             int64          `json:"is_private"`
	IsDraft               int64          `json:"is_draft"`
	AudioFilePath         sql.NullString `json:"audio_file_path"`
	TranscriptionStatus   string         `json:"transcription_status"`
	CreatedAtUtc          int64          `json:"created_at_utc"`
	TrackableValueID      sql.NullInt64  `json:"trackable_value_id"`
	TrackableDefinitionID sql.NullInt64  `json:"trackable_definition_id"`
	ValueInt              sql.NullInt64  `json:"value_int"`
	ValueBool             sql.NullInt64  `json:"value_bool"`
	ValueText             sql.NullString `json:"value_text"`
	LocationText          sql.NullString `json:"location_text"`
	TrackableNoteText     sql.NullString `json:"trackable_note_text"`
	TrackableEntryDate    sql.NullString `json:"trackable_entry_date"`
	TrackableCreatedAtUtc sql.NullInt64  `json:"trackable_created_at_utc"`
	TrackableUpdatedAtUtc sql.NullInt64  `json:"trackable_updated_at_utc"`
	TrackableName         sql.NullString `json:"trackable_name"`
	TrackableIcon         sql.NullString `json:"trackable_icon"`
	TrackableValueType    sql.NullString `json:"trackable_value_type"`
	TrackableUnit         sql.NullString `json:"trackable_unit"`
}

func (q *Queries) ListEntries(ctx context.Context, arg ListEntriesParams) ([]ListEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listEntries, arg.UserID, arg.EntryDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntriesRow
	for rows.Next() {
		var i ListEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RecordedAtUtc,
			&i.TimezoneOffsetMinutes,
			&i.EntryDate,
			&i.NoteText,
			&i.IsPrivate,
			&i.IsDraft,
			&i.AudioFilePath,
			&i.TranscriptionStatus,
			&i.CreatedAtUtc,
			&i.TrackableValueID,
			&i.TrackableDefinitionID,
			&i.ValueInt,
			&i.ValueBool,
			&i.ValueText,
			&i.LocationText,
			&i.TrackableNoteText,
			&i.TrackableEntryDate,
			&i.TrackableCreatedAtUtc,
			&i.TrackableUpdatedAtUtc,
			&i.TrackableName,
			&i.TrackableIcon,
			&i.TrackableValueType,
			&i.TrackableUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesByUser = `-- name: ListEntriesByUser :many
SELECT id, user_id, recorded_at_utc, timezone_offset_minutes, entry_date, note_text, is_private, is_draft, audio_file_path, transcription_status, created_at_utc
FROM entries
WHERE user_id = ?
ORDER BY recorded_at_utc DESC
`

func (q *Queries) ListEntriesByUser(ctx context.Context, userID int64) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, listEntriesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RecordedAtUtc,
			&i.TimezoneOffsetMinutes,
			&i.EntryDate,
			&i.NoteText,
			&i.IsPrivate,
			&i.IsDraft,
			&i.AudioFilePath,
			&i.TranscriptionStatus,
			&i.CreatedAtUtc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingTranscriptions = `-- name: ListPendingTranscriptions :many
SELECT id, audio_file_path
FROM entries
WHERE transcription_status = 'pending'
AND audio_file_path IS NOT NULL
`

type ListPendingTranscriptionsRow struct {
	ID            int64          `json:"id"`
	AudioFilePath sql.NullString `json:"audio_file_path"`
}

func (q *Queries) ListPendingTranscriptions(ctx context.Context) ([]ListPendingTranscriptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingTranscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingTranscriptionsRow
	for rows.Next() {
		var i ListPendingTranscriptionsRow
		if err := rows.Scan(&i.ID, &i.AudioFilePath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettings = `-- name: ListSettings :many
SELECT id, user_id, settings_key, settings_value, created_at_utc
FROM settings
WHERE user_id = ?
`

func (q *Queries) ListSettings(ctx context.Context, userID int64) ([]Setting, error) {
	rows, err := q.db.QueryContext(ctx, listSettings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Setting
	for rows.Next() {
		var i Setting
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SettingsKey,
			&i.SettingsValue,
			&i.CreatedAtUtc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrackableDailyDismissalsByUser = `-- name: ListTrackableDailyDismissalsByUser :many
SELECT id, user_id, trackable_definition_id, dismissal_date, dismissed, created_at_utc, updated_at_utc
FROM trackable_daily_dismissals
WHERE user_id = ?
ORDER BY dismissal_date DESC
`

func (q *Queries) ListTrackableDailyDismissalsByUser(ctx context.Context, userID int64) ([]TrackableDailyDismissal, error) {
	rows, err := q.db.QueryContext(ctx, listTrackableDailyDismissalsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrackableDailyDismissal
	for rows.Next() {
		var i TrackableDailyDismissal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TrackableDefinitionID,
			&i.DismissalDate,
			&i.Dismissed,
			&i.CreatedAtUtc,
			&i.UpdatedAtUtc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrackableDefinitions = `-- name: ListTrackableDefinitions :many
SELECT id, user_id, template_id, name, icon, value_type, unit, min_value, max_value, is_sensitive, private_label, category, active, created_at_utc
FROM trackable_definitions
WHERE user_id = ?
`

func (q *Queries) ListTrackableDefinitions(ctx context.Context, userID int64) ([]TrackableDefinition, error) {
	rows, err := q.db.QueryContext(ctx, listTrackableDefinitions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrackableDefinition
	for rows.Next() {
		var i TrackableDefinition
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TemplateID,
			&i.Name,
			&i.Icon,
			&i.ValueType,
			&i.Unit,
			&i.MinValue,
			&i.MaxValue,
			&i.IsSensitive,
			&i.PrivateLabel,
			&i.Category,
			&i.Active,
			&i.CreatedAtUtc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrackableDefinitionsWithDismissal = `-- name: ListTrackableDefinitionsWithDismissal :many
SELECT
    td.id,
    td.user_id,
    td.template_id,
    td.name,
    td.icon,
    td.value_type,
    td.unit,
    td.min_value,
    td.max_value,
    td.is_sensitive,
    td.private_label,
    td.category,
    td.active,
    td.created_at_utc,
    COALESCE(tdd.dismissed, 0) AS dismissed_today
FROM trackable_definitions td
LEFT JOIN trackable_daily_dismissals tdd
       ON tdd.trackable_definition_id = td.id
      AND tdd.user_id = td.user_id
      AND tdd.dismissal_date = ?
WHERE td.user_id = ?
ORDER BY td.name
`

type ListTrackableDefinitionsWithDismissalParams struct {
	DismissalDate string `json:"dismissal_date"`
	UserID        int64  `json:"user_id"`
}

type ListTrackableDefinitionsWithDismissalRow struct {
	ID             int64          `json:"id"`
	UserID         int64          `json:"user_id"`
	TemplateID     sql.NullInt64  `json:"template_id"`
	Name           string         `json:"name"`
	Icon           sql.NullString `json:"icon"`
	ValueType      string         `json:"value_type"`
	Unit           sql.NullString `json:"unit"`
	MinValue       sql.NullInt64  `json:"min_value"`
	MaxValue       sql.NullInt64  `json:"max_value"`
	IsSensitive    int64          `json:"is_sensitive"`
	PrivateLabel   sql.NullString `json:"private_label"`
	Category       string         `json:"category"`
	Active         int64          `json:"active"`
	CreatedAtUtc   int64          `json:"created_at_utc"`
	DismissedToday int64          `json:"dismissed_today"`
}

func (q *Queries) ListTrackableDefinitionsWithDismissal(ctx context.Context, arg ListTrackableDefinitionsWithDismissalParams) ([]ListTrackableDefinitionsWithDismissalRow, error) {
	rows, err := q.db.QueryContext(ctx, listTrackableDefinitionsWithDismissal, arg.DismissalDate, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTrackableDefinitionsWithDismissalRow
	for rows.Next() {
		var i ListTrackableDefinitionsWithDismissalRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TemplateID,
			&i.Name,
			&i.Icon,
			&i.ValueType,
			&i.Unit,
			&i.MinValue,
			&i.MaxValue,
			&i.IsSensitive,
			&i.PrivateLabel,
			&i.Category,
			&i.Active,
			&i.CreatedAtUtc,
			&i.DismissedToday,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrackableValuesByUser = `-- name: ListTrackableValuesByUser :many
SELECT
    tv.id,
    tv.entry_id,
    tv.trackable_definition_id,
    tv.value_int,
    tv.value_bool,
    tv.value_text,
    tv.location_text,
    tv.note_text,
    tv.entry_date,
    tv.created_at_utc,
    tv.updated_at_utc
FROM trackable_values tv
JOIN entries e ON e.id = tv.entry_id
WHERE e.user_id = ?
ORDER BY tv.created_at_utc DESC
`

func (q *Queries) ListTrackableValuesByUser(ctx context.Context, userID int64) ([]TrackableValue, error) {
	rows, err := q.db.QueryContext(ctx, listTrackableValuesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrackableValue
	for rows.Next() {
		var i TrackableValue
		if err := rows.Scan(
			&i.ID,
			&i.EntryID,
			&i.TrackableDefinitionID,
			&i.ValueInt,
			&i.ValueBool,
			&i.ValueText,
			&i.LocationText,
			&i.NoteText,
			&i.EntryDate,
			&i.CreatedAtUtc,
			&i.UpdatedAtUtc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebauthnCredentialsByUser = `-- name: ListWebauthnCredentialsByUser :many
SELECT id, user_id, credential_id, public_key, sign_count, transports, created_at_utc
FROM webauthn_credentials
WHERE user_id = ?
ORDER BY created_at_utc DESC
`

func (q *Queries) ListWebauthnCredentialsByUser(ctx context.Context, userID int64) ([]WebauthnCredential, error) {
	rows, err := q.db.QueryContext(ctx, listWebauthnCredentialsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebauthnCredential
	for rows.Next() {
		var i WebauthnCredential
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CredentialID,
			&i.PublicKey,
			&i.SignCount,
			&i.Transports,
			&i.CreatedAtUtc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTranscriptionFailed = `-- name: MarkTranscriptionFailed :exec
UPDATE entries
SET transcription_status = 'failed'
WHERE id = ?
`

func (q *Queries) MarkTranscriptionFailed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markTranscriptionFailed, id)
	return err
}

const updateEntryTranscription = `-- name: UpdateEntryTranscription :exec
UPDATE entries
SET note_text = ?,
    is_draft = 0,
    transcription_status = 'completed'
WHERE id = ?
`

type UpdateEntryTranscriptionParams struct {
	NoteText sql.NullString `json:"note_text"`
	ID       int64          `json:"id"`
}

func (q *Queries) UpdateEntryTranscription(ctx context.Context, arg UpdateEntryTranscriptionParams) error {
	_, err := q.db.ExecContext(ctx, updateEntryTranscription, arg.NoteText, arg.ID)
	return err
}

const updateTrackableValueInt = `-- name: UpdateTrackableValueInt :one
UPDATE trackable_values
SET value_int = ?, updated_at_utc = ?
WHERE id = ?
RETURNING id, entry_id, trackable_definition_id, value_int, value_bool, value_text, location_text, note_text, entry_date, created_at_utc, updated_at_utc
`

type UpdateTrackableValueIntParams struct {
	ValueInt     sql.NullInt64 `json:"value_int"`
	UpdatedAtUtc sql.NullInt64 `json:"updated_at_utc"`
	ID           int64         `json:"id"`
}

func (q *Queries) UpdateTrackableValueInt(ctx context.Context, arg UpdateTrackableValueIntParams) (TrackableValue, error) {
	row := q.db.QueryRowContext(ctx, updateTrackableValueInt, arg.ValueInt, arg.UpdatedAtUtc, arg.ID)
	var i TrackableValue
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.TrackableDefinitionID,
		&i.ValueInt,
		&i.ValueBool,
		&i.ValueText,
		&i.LocationText,
		&i.NoteText,
		&i.EntryDate,
		&i.CreatedAtUtc,
		&i.UpdatedAtUtc,
	)
	return i, err
}

const updateTrackableValueText = `-- name: UpdateTrackableValueText :one
UPDATE trackable_values
SET value_text = ?, updated_at_utc = ?
WHERE id = ?
RETURNING id, entry_id, trackable_definition_id, value_int, value_bool, value_text, location_text, note_text, entry_date, created_at_utc, updated_at_utc
`

type UpdateTrackableValueTextParams struct {
	ValueText    sql.NullString `json:"value_text"`
	UpdatedAtUtc sql.NullInt64  `json:"updated_at_utc"`
	ID           int64          `json:"id"`
}

func (q *Queries) UpdateTrackableValueText(ctx context.Context, arg UpdateTrackableValueTextParams) (TrackableValue, error) {
	row := q.db.QueryRowContext(ctx, updateTrackableValueText, arg.ValueText, arg.UpdatedAtUtc, arg.ID)
	var i TrackableValue
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.TrackableDefinitionID,
		&i.ValueInt,
		&i.ValueBool,
		&i.ValueText,
		&i.LocationText,
		&i.NoteText,
		&i.EntryDate,
		&i.CreatedAtUtc,
		&i.UpdatedAtUtc,
	)
	return i, err
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO settings (
    user_id,
    settings_key,
    settings_value,
    created_at_utc
)
VALUES (?, ?, ?, ?)
ON CONFLICT(user_id, settings_key)
DO UPDATE SET settings_value = excluded.settings_value
`

type UpsertSettingParams struct {
	UserID        int64          `json:"user_id"`
	SettingsKey   string         `json:"settings_key"`
	SettingsValue sql.NullString `json:"settings_value"`
	CreatedAtUtc  int64          `json:"created_at_utc"`
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertSetting,
		arg.UserID,
		arg.SettingsKey,
		arg.SettingsValue,
		arg.CreatedAtUtc,
	)
	return err
}

const upsertTrackableDailyDismissal = `-- name: UpsertTrackableDailyDismissal :one
INSERT INTO trackable_daily_dismissals (
    user_id,
    trackable_definition_id,
    dismissal_date,
    dismissed,
    created_at_utc,
    updated_at_utc
)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(user_id, trackable_definition_id, dismissal_date)
DO UPDATE SET
    dismissed = excluded.dismissed,
    updated_at_utc = excluded.updated_at_utc
RETURNING id, user_id, trackable_definition_id, dismissal_date, dismissed, created_at_utc, updated_at_utc
`

type UpsertTrackableDailyDismissalParams struct {
	UserID                int64  `json:"user_id"`
	TrackableDefinitionID int64  `json:"trackable_definition_id"`
	DismissalDate         string `json:"dismissal_date"`
	Dismissed             int64  `json:"dismissed"`
	CreatedAtUtc          int64  `json:"created_at_utc"`
	UpdatedAtUtc          int64  `json:"updated_at_utc"`
}

func (q *Queries) UpsertTrackableDailyDismissal(ctx context.Context, arg UpsertTrackableDailyDismissalParams) (TrackableDailyDismissal, error) {
	row := q.db.QueryRowContext(ctx, upsertTrackableDailyDismissal,
		arg.UserID,
		arg.TrackableDefinitionID,
		arg.DismissalDate,
		arg.Dismissed,
		arg.CreatedAtUtc,
		arg.UpdatedAtUtc,
	)
	var i TrackableDailyDismissal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TrackableDefinitionID,
		&i.DismissalDate,
		&i.Dismissed,
		&i.CreatedAtUtc,
		&i.UpdatedAtUtc,
	)
	return i, err
}
