// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateTrackableDefinition(ctx context.Context, arg CreateTrackableDefinitionParams) (TrackableDefinition, error)
	CreateTrackableValue(ctx context.Context, arg CreateTrackableValueParams) (TrackableValue, error)
	DeleteEntry(ctx context.Context, arg DeleteEntryParams) error
	FindEntryTrackableValue(ctx context.Context, arg FindEntryTrackableValueParams) (TrackableValue, error)
	FindRecentTrackableValue(ctx context.Context, arg FindRecentTrackableValueParams) (TrackableValue, error)
	GetAvailableTrackableTemplateByID(ctx context.Context, arg GetAvailableTrackableTemplateByIDParams) (TrackableTemplate, error)
	GetEntryByID(ctx context.Context, arg GetEntryByIDParams) (Entry, error)
	GetEntryWithTrackables(ctx context.Context, arg GetEntryWithTrackablesParams) ([]GetEntryWithTrackablesRow, error)
	GetTrackableById(ctx context.Context, arg GetTrackableByIdParams) (TrackableDefinition, error)
	GetTrackableTemplates(ctx context.Context, userID int64) ([]TrackableTemplate, error)
	ListEntries(ctx context.Context, arg ListEntriesParams) ([]ListEntriesRow, error)
	ListSettings(ctx context.Context, userID int64) ([]Setting, error)
	ListTrackableDefinitions(ctx context.Context, userID int64) ([]TrackableDefinition, error)
	ListTrackableDefinitionsWithDismissal(ctx context.Context, arg ListTrackableDefinitionsWithDismissalParams) ([]ListTrackableDefinitionsWithDismissalRow, error)
	UpdateTrackableValueInt(ctx context.Context, arg UpdateTrackableValueIntParams) (TrackableValue, error)
	UpdateTrackableValueText(ctx context.Context, arg UpdateTrackableValueTextParams) (TrackableValue, error)
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) error
	UpsertTrackableDailyDismissal(ctx context.Context, arg UpsertTrackableDailyDismissalParams) (TrackableDailyDismissal, error)
}

var _ Querier = (*Queries)(nil)
